### ISSUE TITLE
RFE: documentation for funelim, simp, etc

### ISSUE THREAD

**Issue by ANogin** [mattam82/Coq-Equations#110]
The current documentation does a decent job of explaining how to define equations, but not as good at explaining how to use them once they are defined. I am trying to guess how to prove things from examples - but once something does not work exactly as it did in the example, I am pretty much stuck. Or do I just not know where to look? Thanks!

**Comment by mattam82** [comment]
I've added a more complete documentation on the generated definitions and available tactics, which will be released with the new version (still waiting for 8.9 to be announced).
