### ISSUE TITLE
Regression - failes to prove some obligations

### ISSUE THREAD

**Issue by ANogin** [mattam82/Coq-Equations#119]
With the latest v8.8 the following code
```
From Coq.Lists Require Import List.
From Equations Require Import Equations.

(* This type is from VST: https://github.com/PrincetonUniversity/VST/blob/v2.1/floyd/compact_prod_sum.v#L6 *)
Fixpoint compact_prod (T: list Type): Type :=
  match T with
  | nil => unit
  | t :: nil => t
  | t :: T0 => (t * compact_prod T0)%type
  end.

Record rec1 {MT : Type} :=
  { field1 : MT }.

Record rec2 {MT : Type} :=
  { field2 : list (@rec1 MT) }.

Inductive MT :=
| Prod : @rec2 MT -> MT.

Equations foo_type (t : MT) : Type :=
  foo_type (Prod u) :=
    (compact_prod (List.map (fun t => foo_type (field1 t)) (field2 u))).
```
results in
```
Solving obligations automatically...
1 obligation remaining
Obligation 1 of foo_type_ind_fun: (forall t : MT, foo_type_ind t (foo_type t)).
```
To the best of my recollection, this was not the case very recently (yesterday?), although there is a chance I missed it, and I have not tried doing a careful bisection. Interestingly, if I define `rec2` with `field2: list MT` with a corresponding replacement of `(fun t => foo_type (field1 t))` with just `foo_type`, then it works correctly.

**Comment by ANogin** [comment]
P.S.
```
Equations foo_type (t : MT) : Type :=
  foo_type (Prod u) :=
    (compact_prod (List.map (compose foo_type field1) (field2 u))).
```
seems to work correctly too.

**Comment by ANogin** [comment]
P.P.S. But the compose version does not work later on, when its use results in Coq failing to unify `foo_type (field1 hd) * ?A` with `compact_prod (map (foo_type ∘ field1) (hd :: tl)`...

**Comment by mattam82** [comment]
I don't believe this could "work" in previous versions. Certainly the `foo_type` recursive call was just not recognized in the previous versions.

You have to look at the produced inductive graph to see the problem.
- for the compose version, you don't get any recognized recursive call as the recursive function is not applied to its structural argument and the eliminator is useless.
- for the first version, the recursive call is too general and cannot be proven:
```
Inductive foo_type_ind : MT -> Type -> Prop :=
    foo_type_ind_equation_1 : forall r : rec2,
                              (forall t : rec1, foo_type_ind (field1 t) (foo_type (field1 t))) ->
                              foo_type_ind (Prod r)
                                (compact_prod
                                   (map (fun t : rec1 => foo_type (field1 t)) (field2 r)))
```
  Here there is no relation between the properties for `(field1 t)` and the initial `(Prod r)` value.

- In the following version, the correct elimination principle is found:
```
Equations foo_type (t : MT) : Type :=
{ foo_type (Prod u) :=
    (compact_prod (foo_type_l (field2 u))) }
where foo_type_l (l : list (@rec1 MT)) : list Type := {
  foo_type_l nil := nil;        
  foo_type_l (cons hd tl) := foo_type (field1 hd) :: foo_type_l tl }.
```
The graph becomes:
```
Inductive foo_type_ind : MT -> Type -> Prop :=
    foo_type_ind_equation_1 : forall r : rec2,
                              foo_type_ind_1 (field2 r) (foo_type_l (field2 r)) ->
                              foo_type_ind (Prod r) (compact_prod (foo_type_l (field2 r)))
  with foo_type_ind_1 : list rec1 -> list Type -> Prop :=
    foo_type_ind_1_equation_1 : foo_type_ind_1 [] []
  | foo_type_ind_1_equation_2 : forall (r : rec1) (l : list rec1),
                                foo_type_ind (field1 r) (foo_type (field1 r)) ->
                                foo_type_ind_1 l (foo_type_l l) ->
                                foo_type_ind_1 (r :: l) (foo_type (field1 r) :: foo_type_l l)
```
Here `foo_type_ind_1` relates `(field2 r)` to the result of `(foo_type_l (field2 r)`, recognizing the pointwise recursive calls to `foo_type`.
In general you have to reproduce the combinators under which you are doing nested recursive calls, and you can prove afterwards that they are equivalent to a `List.map` or some such application. Letting the tool automatically infer this will require some work :)

**Comment by mattam82** [comment]
This cannot be fixed without some automatic recognition of nested calls, so closing for now.
