### ISSUE TITLE
Should equations know to split cases when necessary?

### ISSUE THREAD

**Issue by ANogin** [mattam82/Coq-Equations#124]
Not a big deal, but in the following contrived example simplified from something meaningful, but complicated
```
From Equations Require Import Equations.

Equations (struct l) foo (f: option (nat -> nat)) (l: list nat) : list nat :=
  foo None _ := [];
  foo (Some f) nil := nil;
  foo (Some f) (cons hd tl) := cons (f hd) tl.
```
results in undischarged obligations. If the None case is split into nil/cons cases, everything of course works as expected. Is in unreasonable to expect equations know how to do this for me, so that I can specify things more concisely? ;)

**Comment by mattam82** [comment]
It should be able to derive the equations automatically indeed.
Le mer. 20 juin 2018 à 03:25, Aleksey Nogin <notifications@github.com> a
écrit :

**Comment by mattam82** [comment]
Now the (concise) equation and eliminator go through.
