### ISSUE TITLE
dependent elimination unnecessarily normalizes terms

### ISSUE THREAD

**Issue by andres-erbsen** [mattam82/Coq-Equations#129]
I would like to following file to be processed without issues, as it would when using `destruct` instead of `dependent elimination`. Currently, the first goal is instant, the second one takes a couple of seconds, and the third one did not finish in a couple of minutes. This problem showed up in an piece of proof automation when trying to replace `dependent destruction` with `dependent elimination` to remove the usage of axioms.

~~~~~
Require Import Equations.Equations.

Fixpoint slow n : unit := match n with O => tt | S n => match slow n with tt => slow n end end.
Opaque slow. (* should not be necessary, and doesn't help anyway *)

Goal slow  1 = tt /\ True -> True. intros H. dependent elimination H. assumption. Qed.
Goal slow 20 = tt /\ True -> True. intros H. dependent elimination H. assumption. Qed.
Goal slow 32 = tt /\ True -> True. intros H. dependent elimination H. assumption. Qed.
Goal slow 400 = tt /\ True -> True. intros H. dependent elimination H. assumption. Qed.
Goal slow 5000 = tt /\ True -> True. intros H. dependent elimination H. assumption. Qed.
~~~~~

**Comment by mattam82** [comment]
Hmm, one can use depelim in that case, and I've an upcoming version which ensures that depelim doesn't you axioms. I'll investigate the dependent elimination variant.

**Comment by mattam82** [comment]
Indeed, there was an agressive normalization happening during elimination, now removed.
