### ISSUE TITLE
Equations command breaks Write State

### ISSUE THREAD

**Issue by greenrd** [mattam82/Coq-Equations#13]
If you put a Write State command in after the first Equation in test-suite/Basics.v, like this:

Require Import Program Equations Bvector List.
Require Import Relations.
Require Import DepElimDec.

Module TestF.

  Equations f (n : nat) : nat :=
  f 0 := 42 ;
  f (S m)  with f m :=
  {
    f (S m) IH := _
  }.
  
  Next Obligation. exact IH. Defined.
  Write State bisect.
End TestF.

you get:

Anomaly: Uncaught exception Invalid_argument("output_value: functional value").
Please report.

**Comment by mattam82** [comment]
Fixed now.
