### ISSUE TITLE
Please make your project compile with -w "+compatibility-notation"

### ISSUE THREAD

**Issue by Zimmi48** [mattam82/Coq-Equations#133]
Please make your project compile with `-w "+compatibility-notation"` to prepare for the Coq 8.9 release. We would appreciate if this could be done ASAP. If you have trouble doing so, please raise your concern at coq/coq#8383.

**Comment by mattam82** [comment]
Fixed in 4d26ac6

**Comment by Zimmi48** [comment]
Thanks!
