### ISSUE TITLE
Mutual well-founded recursion?

### ISSUE THREAD

**Issue by HuStmpHrrr** [mattam82/Coq-Equations#143]
Hi, I am working on well-founded mutual recursion using Equations, and Coq generates following obligation for me:

```
1 subgoal (ID 617)
  
  ty_syn_func : env -> trm -> list atom -> error + Tc typ
  x : env -> trm -> typ -> error + Tc ()
  G : env
  t : trm
  T : typ
  ty_ch_func : (env -> trm -> list atom -> error + Tc typ) ->
               (env -> trm -> typ -> error + Tc ()) ->
               env ->
               forall t0 : trm,
               typ -> trm_struct_measure t0 < trm_struct_measure t -> error + Tc ()
  ============================
  add_pattern (error + Tc ()) (hide_pattern ty_ch_func)
```

I don't understand what that obligation means. When I unfold `add_pattern` and `hide_pattern`, I discharge the goal (trivially), and it gives follow error:

```
ty_syn_func_obligation_1 is defined
No more obligations remaining
ty_syn_func is defined
Error:
Recursive definition of ty_ch_func is ill-formed.
In environment
ty_syn_func : env -> trm -> list atom -> error + Tc typ
G : env
t : trm
V : list atom
ty_ch_func : env -> trm -> typ -> error + Tc ()
G0 : env
t0 : trm
T : typ
Recursive call to ty_ch_func has not enough arguments.
Recursive definition is:
"fun (G : env) (t : trm) (T : typ) =>
 ty_ch_func_functional ty_syn_func ty_ch_func
   (fix ty_ch_defs_func (G0 : env) (ds : defs) (DS : decs) {struct DS} :
      error + Tc () :=
      ty_ch_defs_func_functional ty_syn_func ty_ch_func ty_ch_defs_func G0 ds DS) G t T".
```

I don't understand this message either. I'd imagine it's because I discharged the goal too trivially. Could you help me understand it?

**Comment by HuStmpHrrr** [comment]
Hi Matthieu,

I think I discovered a bug when well-founded recursion and nested recursion got mixed together:

 ```coq
 Variable A : Type.

  Inductive forest : Type :=
  | emp : A -> forest
  | tree : list forest -> forest.

  Equations fweight (f : forest) : nat :=
    {
      fweight emp := 1;
      fweight (tree l) := 1 + lweight l 
    }
  where lweight (l : list forest) : nat :=
    {
      lweight nil := 1;
      lweight (cons f l') := fweight f + lweight l'
}.

  Equations flatten (f : forest) : list A :=
    {
      flatten f by rec (fweight f) lt :=
      flatten emp := nil;
      flatten (tree l) :=
        let fix func (fs : list forest) (t : tail_of fs l) : list A :=
            match fs as fs0 return tail_of fs0 l -> list A with
            | nil => fun _ => nil
            | cons f fs' =>
              fun t' => app (flatten f) (func fs' (tail_of_decons t'))
            end t in
        func l (t_refl _)
    }.
  Next Obligation.
    apply tail_of_fweight in t'.
    simpl in t'.
    pose proof (lweight_neq_0 fs').
    simp fweight. lia.
Fail Qed.
```

Full self contained repo:

https://gist.github.com/HuStmpHrrr/50d7f5c12335e79ca3432d308ef8f4c7

I am nowhere close to an expert. I guess I am hitting a case where the code got transformed in a wrong way. One way to get away with this is to actually leave `func`'s implementation a hole, and then implement it in proof mode when obligation is hit. however, this prevents proper unfold function from being generated.

In my repo I also discovered other bugs. say, `funelim` is not applicable for some reason.

**Comment by mattam82** [comment]
Hi I just seen this. I guess mixing well founded recursion and fix is not handled well. Did you try defining `func` with a local where clause instead?

**Comment by HuStmpHrrr** [comment]
Hi,

I wanted to use where clause, but I don't fully understand how the scope of where clause works. Here is one of my attempts:

```coq
  Equations flatten (f : forest) : list A :=
    {
      flatten f by rec (fweight f) lt :=
      flatten emp := nil;
      flatten (tree l) := func l (t_refl _)
        where func (fs : list forest) (t : tail_of fs l) : list A :=
              {
                func nil _ := nil;
                func (cons f fs') t' := app (flatten f) (func fs' (tail_of_decons t'))
              }
    }.
  ```

Then in the where clause, the `cons` case for `func`, it says

```
The variable func was not found in the current environment.
```

This is mysterious to me. It seems to me sometimes where works, but not always. My observation is when it's structural recursion it will work. I suppose well-founded recursion is not fully supported yet?

I discovered a workaround for the problem I encountered in this issue, but it would be nice if you can show me how you would do it in Equations.

**Comment by mattam82** [comment]
Hi, indeed where clauses are a bit fragile right now, I’m currently rewriting that part so that both structural and well-founded local where clauses can cohabit within structural or well-founded definitions. The way you write it func is local to the second clause. Currently local where clauses are not recursive so func is not « in the context » here. The only way out currently would be to make flatten and func structurally recursive and lift the where clause out of the func definition as a toplevel ˋwhereˋ, as you did to define the weight measure. I’ll update the issue when I’m done refactoring, which should make your definition go through. My branch also fixes issues with funelim not being applicable (e.g. conclusion depends on foo errors), among other fixes.

**Comment by HuStmpHrrr** [comment]
great, thx. please let me know when you have a fix. I would love to help testing it. I also discovered a number of other issues when Equations works with sections and modules, and gives unexpected behavior, but I guess I will wait for your fix first and see if those issues persist.
