### ISSUE TITLE
Master doesn't compile with older version of Coq

### ISSUE THREAD

**Issue by HuStmpHrrr** [mattam82/Coq-Equations#162]
I am using Coq 8.8.0 but it seems coq_makefile doesn't recognize .mlg file:

```
coq_makefile -f _CoqProject -o Makefile
```

Is that the case that it's unsupported in my version? 8.8.0 is old but not that old, so I guess I should try 8.9 as README says master branch is for Coq's master?

**Comment by mattam82** [comment]
Indeed, the master branch follows Coq's master, while 8.8 and 8.9 follow the respective Coq's branches. The upcoming release will work with all three versions, so no need to update for that.
