### ISSUE TITLE
Wrong binding of infix -

### ISSUE THREAD

**Issue by gert-smolka** [mattam82/Coq-Equations#166]
From Equations Require Import Equations.

Equations minus : nat -> nat -> nat :=
  { 0 - n := 0 ;
    S m - 0 := S m ;
    S m - S n := m - n }
where "x - y" := (minus x y).

Set Printing All.
Goal forall x y : nat, x >= y -> (x - y) + y = x.

(* Nat.sub is used *)

**Comment by mattam82** [comment]
Hi Gert, this is due to the scoping rules of Coq, nothing to do with Equations. As - is used under + and + declares its arguments to be in nat_scope, the - notation in nat_scope is taking precedence. You can use `: nat_scope` to override the Nat.sub notation but that's all I can suggest here.
