### ISSUE TITLE
funelim does not work fully as an eliminator

### ISSUE THREAD

**Issue by HuStmpHrrr** [mattam82/Coq-Equations#168]
I suppose you have mentioned it once before, that we might have to use `pose proof (fun_elim (f := foobar))` to work around this: https://github.com/mattam82/Coq-Equations/issues/143#issuecomment-451282346, but since there is no issue for that, I am creating this issue.

I am somewhat surprised that `funelim` seems weaker than the previous version now. In the case of with pattern, the old `funelim` is able to look into the with pattern, but now it fails to. but at least in my use cases, `pose proof` solution seems to overwhelmingly beat `funelim` by far, so I will be stick to that for a while.

**Comment by mattam82** [comment]
I’m not sure what you mean by “look into the with”, do you have an example?

**Comment by HuStmpHrrr** [comment]
I meant `the with pattern`. in the previous version, `funelim` will go into with patterns as deep as possible, but it seems now it stops at a point and requires manual rewrite and simpl to continue the evaluation. I will try to come up with an example.

**Comment by HuStmpHrrr** [comment]
I've got no idea why `funelim` doesn't reduce the cases to the end for the actual project I work on, but it does for the simple examples I create.

I notice that when it doesn't, there is a equality `Heqcall` generated, in contrast to `Heq`, Heq0` etc. why's the distinction?

**Comment by mattam82** [comment]
If Heqcall is left then I would guess you have some unsolvable or unsimplifiable equality between the initial arguments of your call and the ones of the cases that are considered. Or it's just that the simplification is not doing its job correctly. Can you give an example goal where you see that?

**Comment by HuStmpHrrr** [comment]
actually in my project, a very simple `Equations` can already generate such `Heqcall`. For example:

```coq

Equations exposure_func (G : env) (T : typ) : typ by wf (length G) lt :=
  {
    exposure_func G T with is_sel_dec T => {
    | inleft (existT _ (avar_b _) (exist _ A _)) => typ_top;
    | inleft (existT _ (avar_f x) (exist _ A _)) with split_at x G => {
      | None => typ_top;
      | Some (existT _ T' (existT _ G1 _)) with exposure_func G1 T' => {
        | typ_bot => typ_bot;
        | typ_rcd DS with decs_typ_lookup A DS => {
          | None => typ_top;
          | Some (pair _ U) => exposure_func G1 U
          };
        | typ_obj DS
            with expo_mu_func (collect_ty_labs DS) x A (open x DS) => {
          | (pair _ U) => exposure_func G1 U
          };
        | _ => typ_top
        }
      };
    | inright _ => T
    }
  }.
```

and the following theorem

```coq
  Theorem exposure_func_sound_wrt_spec : forall G T U,
    exposure_func G T = U ->
    exposure G T U.
  Proof.
    intros. funelim (exposure_func G T).
```

In the very first case, it generates following context

```
10 subgoals (ID 5519)
  
  T0 : typ
  n : nat
  x : typ_label
  e : T0 = n ⋅ x
  G0 : env
  Heq : is_sel_dec T0 =
        inleft
          (existT (fun x : avar => {A : typ_label | T0 = x ⋅ A}) n
             (exist (fun A : typ_label => T0 = n ⋅ A) x e))
  Heqcall : ⊤ = exposure_func G0 T0
  ============================
  exposure G0 T0 (exposure_func G0 T0)
```

which seems to represent the result as `Heqcall`.

**Comment by HuStmpHrrr** [comment]
there is a more complicated case from a different theorem, which has both `Heqcall` and `Heq`: https://pastebin.com/Wdd33vXC

this context is generate by this clause
```
      ty_syn_ch_func G (trm_let (Some T) t1 t2) (inl V)
        with ty_syn_ch_func G t1 (inr T) => {
      | inl e => inl e;
      | inr (inl msgs) =>
        inr (inl ("synthesizer: failed to check the binding term in let case"
                    :: msgs));
      | inr (inr _) with pick_fresh_var => {
        | exist _ x _ =>
          ty_syn_ch_func (x ~ T ++ G) (open x t2) (inl (x :: V))
                         !!!> "synthesizer: failed to synthesize the body in let case"
        }
      };
```
which should follow Equations' syntax fairly tightly.

notice that in the context

```
  H2 : ty_syn_ch_func G0 (lett t0 as t inn t1) (inl l0) = inr (inr T)
  Heqcall : (ty_syn_ch_func ([(x, t)] ++ G0) (open x t1) (inl (x :: l0))
             !!!> "synthesizer: failed to synthesize the body in let case") =
            ty_syn_ch_func G0 (lett t0 as t inn t1) (inl l0)
```

In the last version, `ty_syn_ch_func G0 (lett t0 as t inn t1) (inl l0)` in `H2` would have been replaced by the left hand side of `Heqcall`.

**Comment by mattam82** [comment]
I see, these equations are left over because we can't always simplify them without losing provability, although in your case it might be benign. I guess you can either do an automatic rewrite of Heqcall in * or indeed, call the eliminator by hand. In case the function call you are eliminating is only on variables and the goal is properly generalized by anything that depends on them, applying the eliminator won't lose information (this is what those equalities are here to ensure). In the future I hope to improve funelim so that it detects this case and apply the following tactic instead, which just applies the lemma (using higher-order unification to find the predicate):
```
  Ltac apply_funelim c :=
  let elimc := get_elim c in
  let elimfn := match elimc with fun_elim (f:=?f) => constr:(f) end in
  let elimn := match elimc with fun_elim (n:=?n) => constr:(n) end in
  let elimt := make_refine elimn elimc in
  unshelve refine_ho elimt; cbv beta; intros.
```

**Comment by HuStmpHrrr** [comment]
but why the simple examples won't give those `Heqcall`? is that because I used subset types?

I don't fully understand in what case the previous `funelim` makes goal unprovable. what i find the current `funelim` inconvenient is that the proof script now requires some fragile tactic sequence which tries to guess an execution order:

```coq
        try rewrite Heq0 in *; simpl in *; try rewrite Heq in *;
          simpl in *; try congruence.
      all:try rewrite <- Heqcall in *.
```

this makes the proof script less robust, because it might break, for example, after a code change and `Heq1` is introduced.

**Comment by mattam82** [comment]
It might be related to subset types indeed, or because the simplifications done in the tactic `FunctionalInduction.funelim_sig_tac` manage to simplify the elimination in the simple examples and not in those ones. You can try and play with it if you like. Otherwise, I have found a little improvement for tactic that does not introduce equalities in the simple case:
```
 Ltac apply_args c elimc k :=
    match c with
    | _ ?a ?b ?c ?d ?e ?f => k uconstr:(elimc a b c d e f)
    | _ ?a ?b ?c ?d ?e => k uconstr:(elimc a b c d e)
    | _ ?a ?b ?c ?d => k uconstr:(elimc a b c d)
    | _ ?a ?b ?c => k uconstr:(elimc a b c)
    | _ ?a ?b => k uconstr:(elimc a b)
    | _ ?a => k uconstr:(elimc a)
    end.

  Ltac get_first_elim c :=
    match c with
    | ?f ?a ?b ?c ?d ?e ?f => get_elim (f a b c d e f)
    | ?f ?a ?b ?c ?d ?e => get_elim (f a b c d e)
    | ?f ?a ?b ?c ?d => get_elim (f a b c d)
    | ?f ?a ?b ?c => get_elim (f a b c)
    | ?f ?a ?b => get_elim (f a b)
    | ?f ?a => get_elim (f a)
    end.

  Ltac apply_funelim c :=
    let elimc := get_first_elim c in
    let elimfn := match elimc with fun_elim (f:=?f) => constr:(f) end in
    let elimn := match elimc with fun_elim (n:=?n) => constr:(n) end in
    let elimt := make_refine elimn elimc in
    apply_args c elimt ltac:(fun elimc =>
                               unshelve refine_ho elimc; cbv beta).
```

This one you can call as `apply_funelim (fn args)`.

**Comment by mattam82** [comment]
The previous version might also have used JMeq/heterogeneous equality to simplify calls which is more powerful in an essential way, but introduces an axiom.

**Comment by HuStmpHrrr** [comment]
thanks. the tactics above rocks.

**Comment by mattam82** [comment]
I've added it to the standard library of tactics and documented it in the reference manual, explaining the tradeoffs of the various funelim calling methods.
