### ISSUE TITLE
[warnings] Please fix OCaml warnings

### ISSUE THREAD

**Issue by ejgallego** [mattam82/Coq-Equations#175]
Dear devs,

in Coq we are considering requiring plugins in the CI to use the same set of compiler flags for warnings than the main Coq tree (c.f. https://github.com/coq/coq/pull/9605 ), in particular, this means that the plugins should now compile warning-free, except for deprecation notices.

Note that some of the raised warnings are really fatal, [like missing match cases].

Please, try to fix OCaml warnings present in your codebase, thanks!

**Comment by mattam82** [comment]
It has no warnings anymore, so closing.

**Comment by ejgallego** [comment]
Great, thanks @mattam82
