### ISSUE TITLE
Avoid reducing user-given terms?

### ISSUE THREAD

**Issue by Janno** [mattam82/Coq-Equations#176]
I've been trying to use Equations with Mtac2 where better support for dependent types is very much needed and appreciated. So far I found it to be much, much, much better than `Program`. *However*, Equations seems to be in the habit of reducing user-given terms—especially let bindings. The following (somewhat nonsensical) Mtac2 program demonstrates this:

```coq
From Equations Require Import Equations.
From Mtac2 Require Import Mtac2.
Equations test (x : nat) : M (x = x) :=
  test x =>
  mmatch x as x return M (x = x) with
  | (let n := 2 + 2 in n) =n> M.ret (eq_refl)
  end.
Print test. (* beautified output for demonstration purposes:
test  = fun x : nat => 
  mmatch x in nat as x0 return M x0 = x0 with 
  | 2 + 2 =n> M.ret eq_refl 
  end
*)
```
Note the absence of the let binding. This will drastically change the meaning of the Mtac2 program, which does a non-reducing comparison between `x` and the candidate in the branch and will now trigger on just addition instead of let-bound addition.

Could Equations support a mode where it keeps terms written explicitly by the user exactly as they are?

**Comment by mattam82** [comment]
Hmm, this is definitely a bug and not expected.

**Comment by mattam82** [comment]
I was being very naughty and betadeltazeta reduced terms.
