### ISSUE TITLE
Syntax error: [tactic:equation_options] expected after 'Equations' (in [vernac:command])

### ISSUE THREAD

**Issue by gert-smolka** [mattam82/Coq-Equations#179]
With Proof General when I process 
`Equations? ... `
after backtracking for the second time I get 
`Syntax error: [tactic:equation_options] expected after 'Equations' (in [vernac:command])`
The problem is with the `?`.  The first time I process the `Equations?` command everything is fine.

**Comment by mattam82** [comment]
Yes, I've been experimenting this again. @herbelin or @ppedrot would you know why this happens? It seems related to the parser, I declare the `Equations?` proof opening variant using:
```
VERNAC COMMAND EXTEND Define_equations_refine CLASSIFIED BY { classify_equations }
| #[ poly = polymorphic; program_mode = program ] [ "Equations?" equation_options(opt) equations(eqns) ] ->
    { Equations.equations ~poly ~program_mode ~open_proof:true opt (fst eqns) (snd eqns) }
END
```

**Comment by xuanruiqi** [comment]
I have been getting the same bugs today. Restarting the Coq process helps, but having to restart all time is annoying.

**Comment by mattam82** [comment]
Yep it’s annoying, I think it happens only when you backtrack over a `Requie Import`

**Comment by mattam82** [comment]
I'll try to bug Pierre-Marie Pédrot about it, he must know :)

**Comment by mattam82** [comment]
Indeed the fix was not too hard, it seems to work correctly now (fix in master, will be in the final)
