### ISSUE TITLE
Without K no longer working in 8.9?

### ISSUE THREAD

**Issue by jwiegley** [mattam82/Coq-Equations#180]
My [category-theory](https://github.com/jwiegley/category-theory) library uses Equations-8.8 and Coq 8.8. I'm trying to upgrade to 8.9 and equations 1.2-beta, but many of my definitions which succeeded before now fail with:

    Error: [deletion] Cannot simplify without K on type A

Do you know what may have changed that it can no longer simplify?

**Comment by mattam82** [comment]
I just disabled K/UIP by default. Use `Set Equations WithKDec` or `Set Equations WithK` (that one needs the K axiom, which you first need to import using `Require Import Equations.DepElimK`. Note that I just deprecated these flags for a single one named "Equations With UIP" and if you want to use the UIP axiom you'll have to declare yourself an axiom. This is all documented in the manual

**Comment by jwiegley** [comment]
My apologies for not reading the new version of the manual, Matthieu. Everything works as documented. :)
