### ISSUE TITLE
Local options noind and noeqns as global options

### ISSUE THREAD

**Issue by gert-smolka** [mattam82/Coq-Equations#187]
It would be nice to have the local options noind and noeqns also as global options.
Background: I'm using Equations for ordinary function definitions in course material for Coq beginners.  Equational definitions as in Agda are so much nicer than computational definitions with Fixpoint and match.

**Comment by mattam82** [comment]
Yep, easy to add.

**Comment by mattam82** [comment]
That will be in the final release.
