### ISSUE TITLE
Multi with limit 

### ISSUE THREAD

**Issue by TDiazT** [mattam82/Coq-Equations#190]
I defined a function with a multi-with with 3 patterns and I got an error about non-matching clause in the subprogram.

A simple example:
```

  Equations foo (n : nat) : nat :=
    {
      foo 0
        with true, true, true :=
        {
        | true | true | true := 1;
        | _ | _ | _ := 0
        };

      foo _ := 0
          
    }.
```
You get the following message:
```
Error: Non-matching clause in with subprogram:
       2Problem is  |- 0 : n : nat
       And the user patterns are:  0 true true true
```

(With only two clauses it works fine).

Maybe I am not using it correctly?

**Comment by mattam82** [comment]
Ah, good catch, that’s a bug

**Comment by mattam82** [comment]
Fixed in master now.
