### ISSUE TITLE
Undefined universe when providing a proof of wf for Derive Subterm

### ISSUE THREAD

**Issue by kyoDralliam** [mattam82/Coq-Equations#191]
I am trying to derive Subterm for the following definition of a free monad on a signature.
The deriving command leaves me with a proof obligation that the defined relation is indeed well-founded, but the proof does not pass the Qed step, raising a `Error: Anomaly "Universe Top.445 undefined."`.

```Coq
From Equations Require Import Equations.
(* Assuming UIP *)
From Coq.Logic Require Import Eqdep.

Section FreeMonad.

  Variable S : Type.
  Variable P : S -> Type.

  Inductive FreeF A : Type :=
  | retFree : A -> FreeF A
  | opr     : forall s, (P s -> FreeF A) -> FreeF A.

  Derive Subterm for FreeF.

  Lemma LeafNoSubterm : forall A x a, ~(FreeF_subterm _ x (retFree A a)).
  Proof.
    cbv ; intros * H; dependent induction H.
      dependent destruction H; discriminate H.
      assumption.
  Qed.

  Next Obligation.
    red ; induction 0 ; constructor.
    - intros ? H ; exfalso ; revert H. apply LeafNoSubterm.
    - intros ? Hsub ; cbv in Hsub ; dependent induction Hsub.
      dependent destruction H. injection H. intros.
      clear H ; revert f H1 H0. rewrite H2.
      intros. apply EqdepTheory.inj_pair2 in H1. rewrite <- H1.
      apply H0.
      destruct y.
      exfalso ; revert Hsub1 ; apply LeafNoSubterm.
      apply IHHsub2. assumption. assumption.
   (* Error: Anomaly "Universe Top.177 undefined." *)
   Defined.

End FreeMonad.
```

Using Coq 8.8.2 and Equations 1.2beta1

**Comment by mattam82** [comment]
My first guess would be that you shouldn’t interleave the LeafNoSubterm lemma between Derive and Next Obligation. What happens if you prove it using `assert` inside the obligation instead?

**Comment by kyoDralliam** [comment]
The same thing happens when `LeafNoSubterm` is an assert (it was originally an assert that I hoisted out of the `Next Obligation`).

However copy-pasting the definition of `FreeF_directSubterm` and `FreeF_subterm` given by the Derive clause allow me to prove "by hand" that `FreeF_subterm` is well-founded without trouble.

**Comment by mattam82** [comment]
Ok, so its maybe Equations doing wrong with universes, I'll investigate

**Comment by mattam82** [comment]
An easy fix is to do `Derive NoConfusion Subterm for FreeF`, which should derive everything for you (at least in beta2).

**Comment by mattam82** [comment]
The nice thing is that it needs no `inj_pair2` axiom as well :)

**Comment by mattam82** [comment]
If fixed one fundamental issue which was that the subterm derivation was indeed wrongly handling universes, but interleaving Lemmas between Obligations is still a problem in Coq. This will be resolved when we really have entirely functionalized the environment (followup to coq/coq#9129 will bring that at some point).
