### ISSUE TITLE
Set Equations Derive Equations.

### ISSUE THREAD

**Issue by gert-smolka** [mattam82/Coq-Equations#192]
Set Equations Derive Equations.
says 
Warning: There is no option Equations Derive Equations. [unknown-option,option]
in 1.2~beta2+8.9.

Also, opam says
↗ upgrade coq-equations 1.2~beta2+8.9 to 1.2~beta+8.9
where I would expect this to be a downgrade.

**Comment by mattam82** [comment]
That's curious, I thought beta2+8.9 should be greater than beta+8.9. It the option is not in the beta2 version though, but will be in the final release.
