### ISSUE TITLE
*_graph_correct cannot be solved automatically

### ISSUE THREAD

**Issue by umazalakain** [mattam82/Coq-Equations#228]
The error appears with the following function definition:
https://github.com/umazalakain/session-types-coq/blob/4a565fc0af93e282f4dec467bf8c9ff7c1cb6170/src/SessionTypes.v#L241

It says that the obligation `find_graph_correct`, although typechecked successfully, cannot be solved automatically, yet when I change `Equations` to `Equations?` it tells me that there is nothing to proof.

This appears to be related to the `PSelect i (C c) P` clause: everything goes well if the recursion in that clause is removed. Yet, the recursion is on a strictly smaller term, and seems to work in other clauses. To make sure it wasn't somehow related to type inference I provided all arguments explicitly, but no luck.

**Comment by mattam82** [comment]
What happens if you move `find_branches` to a top-level `where` clause instead?

**Comment by umazalakain** [comment]
Hey! Thanks for having a look at this ^_^

I tried to come up with a somewhat smaller case, you'll be find it here https://github.com/umazalakain/session-types-coq/blob/bug/src/SessionTypes.v

In the `PSelect` case, not pattern matching on the channel's type (changing `(C c)` to `c`) makes the bug disappear. Pattern matching on this `c` through a `with` clause works too.

**Comment by mattam82** [comment]
Hmm something fishy still happens.. the graph is now actually generated in all cases and Equations proves it is correct, but it doesn't manage to define the eliminator constant with a strange "Cannot do a fixpoint on a non inductive type.", even weirder, if you `Set Equations Debug` before the definition then the eliminator is defined successfully. Do you not experience this problem anymore?

**Comment by mattam82** [comment]
Well, I fixed the source of the problem now.

**Comment by umazalakain** [comment]
I closed the issue originally because I was cleaning up old stale issues, but damn, nice!
