### ISSUE TITLE
Unbound module Sigma?

### ISSUE THREAD

**Issue by jwiegley** [mattam82/Coq-Equations#23]
I'm trying to build Coq-Equations myself with Coq 8.7, but I run into this build failure:

```
File "src/equations_common.mli", line 380, characters 18-28:
Error: Unbound module Sigma
```

Is there a dependency not specified in the README.md?

**Comment by mattam82** [comment]
You probably have to switch to the 8.7 branch.
Le ven. 10 nov. 2017 à 21:41, John Wiegley <notifications@github.com> a
écrit :

**Comment by jwiegley** [comment]
Thanks!

**Comment by jwiegley** [comment]
I'm seeing this same error now with the v1.0 release. Is that release intended to work for both Coq 8.6 and 8.7?

**Comment by mattam82** [comment]
Nope, there are too many code changes to have the same code works. There is
a v1.0-8.7 tag and release for 8.7
Le mer. 20 déc. 2017 à 19:57, John Wiegley <notifications@github.com> a
écrit :
