### ISSUE TITLE
Simp does not change goal

### ISSUE THREAD

**Issue by SSoelvsten** [mattam82/Coq-Equations#242]
Equations was the topic of the TA session in the course *Functional Programming* this morning, and I and my TA got stuck on using `simp`. A minimal version of the mini-chapter is the following.

```coq
(* Vector Example *)

Inductive vec (A:Type) : nat -> Type := 
  | nil : vec A 0
  | cons : forall n, A -> vec A n -> vec A (S n).

Arguments nil {A}.
Arguments cons {A n}.

Equations head {A n} (v : vec A (S n)) : A :=
head (cons x _) := x.

Equations tail {A n} (v : vec A (S n)) : vec A n :=
tail (cons x v) := v.

(* Exercises: *)
(*
  Using equations, define
    app : forall {A m n}, vec A m -> vec A n -> vec A (m + n).
 *)
Equations app {A m n} (l1 : vec A m) (l2 : vec A n) : vec A (addn m n) :=
  app nil l2 := l2;
  app (cons hd tl) l2 := cons hd (app tl l2).

(*
  Using equations, define
    head_app : forall {A m n} (v : vec A (S m)) (w : vec A n), head v = head (app v w).
 *)
Obligation Tactic := idtac.

Equations head_app {A m n} (v : vec A (S m)) (w : vec A n) : head v = head (app v w) :=
  head_app (cons hd tl) _ := _.
Next Obligation.
  intros. simp head. simp app. simp head. reflexivity. Qed.
```
Without `Obligation Tactic := idtac.` it is automatically proven. Likewise, `reflexivity` is capable of proving it. The weird behaviour is, that after applying `intros. simp head.` the goal is as expected
```coq
hd = head (app (cons hd tl) w)
```
Yet after `simp app.` The goal does **not** change, while we both expected it to turn into
```coq
hd = head (cons hd (app tl w))
```
Technical specifications of interest
- Ubuntu 18.04.3 LTS
- Ocaml/Opam version:
  - ocaml-system.4.05.0
- Opam repos:
  - https://coq.inria.fr/opam/released
  - https://opam.ocaml.org
- Editor: Spacemacs (developer branch)

**Comment by mattam82** [comment]
It does now, this has been fixed.
