### ISSUE TITLE
Anomaly "should not fail here" when using dependent elimination without NoConfusionHom

### ISSUE THREAD

**Issue by kyoDralliam** [mattam82/Coq-Equations#247]
On Equations 1.2, Coq 8.10.0, the following script raises an anomaly.

```coq
From Equations Require Import Equations.

Inductive t : unit -> Type :=
| base : t tt
| strange : t tt  -> t tt.

Derive Subterm for t.
(* One obligation left for well-foundedness *)
Next Obligation.
  apply Transitive_Closure.Acc_clos_trans.
  destruct a as [u a]; revert u a.
  refine (fix IH u a {struct a} := _).
  destruct a.
  - constructor. intros [[] y] Hy.
    simpl in Hy.
    (* without simpl dependent elimination says "Error: This is not an equality between constructors." *)
    dependent elimination Hy.
    (* Error: Anomaly "Uncaught exception Failure("Should not fail here, please report.")." *)
    inversion Hy. (* Works*)
  - constructor. intros [[] y] Hy. inversion Hy. exact (IH tt a).
Defined.
```
When using `dependent elimination` in the second branch, the tactic complains that `NoConfusionHom` should be derived for `t`. Adding `Derive NoConfusionHom for t` then makes `Derive Subterm for t` solve all obligations, and dependent elimination now succeeds if one try to reenact the same proof.

**Comment by mattam82** [comment]
Indeed, there was a bug in dependent elimination which should have realised that it missed the noconfusion instances in the simplified case as well.

**Comment by mattam82** [comment]
Now need to do the simplification explicitely anymore BTW, I also fixed that.
