### ISSUE TITLE
Make install fails to install cmx* files

### ISSUE THREAD

**Issue by amintimany** [mattam82/Coq-Equations#263]
```make install``` simply skips installing ```cmx*``` files with warnings like the following:
```
SKIP src/equations_plugin_mod.cmx since it has no logical path
```
 I tried ```make install``` on the commit tagged ```v1.2.1-8.10``` with ```Coq 8.10```.

**Comment by mattam82** [comment]
Oh, right! You should use v1.2.1-8.10-fix which fixes this (and they are the ones pointed at by the opam package, you didn't try that one?)

**Comment by mattam82** [comment]
@amintimany Can you confirme the newer tag works?

**Comment by amintimany** [comment]
@mattam82 Yes, that one works; thanks.
