### ISSUE TITLE
Inaccessible pattern through datatype index

### ISSUE THREAD

**Issue by pedrotst** [mattam82/Coq-Equations#265]
Consider the following example:

```From Equations Require Import Equations.

Inductive unit_or_double_unit : Type -> Type :=
| Unit : unit_or_double_unit unit
| Double_unit : unit_or_double_unit (unit * unit).

Equations twelve (x : unit_or_double_unit unit): nat :=
  twelve Unit := 12.
```

The definition of `twelve` should be valid, since `Double_unit` would be an inaccessible pattern. However, this will give me the following error:

```
Unable to build a covering for:
twelve x
In context: 
 x : unit_or_double_unit ()
```

In fact, even if I introduce the `Double_unit` pattern the problem still persists

```
Equations twelve (x : unit_or_double_unit unit): nat :=
  twelve Unit := 12;
  twelve Double_unit := 13.
```

I tested this on the following environment:
```
JsCoq (0.10.0~beta1), Coq 8.10+beta1/8991 (May 2019),
   compiled on May 16 2019 8:46:40
 Ocaml 4.07.1 Js_of_ocaml version 3.4.0
```

**Comment by mattam82** [comment]
Indeed, types are not discriminable, e.g. there is in general no proof in Coq that A <> B for A and B : Type, which would be needed to ensure `Double_unit` cannot have type `unit_or_double_unit unit`. In this particular case, `unit` and `unit * unit` are even isomorphic, so there are plenty of models where they would be equal.
