### ISSUE TITLE
Require Equations can break existing obligations

### ISSUE THREAD

**Issue by dunnl** [mattam82/Coq-Equations#274]
**Version**: 
Coq 8.11.1 and Equations 1.2.1+8.11
```
$ coqc --version:
The Coq Proof Assistant, version 8.11.1 (April 2020)
compiled on Apr 18 2020 1:05:33 with OCaml 4.10.0
```
```
$ opam search coq-equations
# Name        # Installed # Synopsis
coq-equations 1.2.1+8.11  A function definition package for Coq
```

**Issue**:
Requiring Equations causes terms to disappear in obligations generated with Program (even if these obligations were generated before requiring Equations).

Example
```
Require Import Coq.Program.Utils.
Program Definition eq_nat_decide (n1 n2 : nat) :  n1 <> n2 :=
    match n1, n2 with
    | _, _ => in_right
    end.
Next Obligation.
```
leaves me in proof state
```
  n1, n2 : nat
  ============================
  n1 <> n2
```

This is fine. But then
```
Require Import Coq.Program.Utils.
Program Definition eq_nat_decide (n1 n2 : nat) :  n1 <> n2 :=
    match n1, n2 with
    | _, _ => in_right
    end.
From Equations Require Equations. (* new *)
Next Obligation.
```
leaves me in proof state
```
  n1 : nat
  ============================
  False
```

This behavior is very sensitive to the type of the Program Definition. E.g the behavior disappears with any of the following types instead of `n1 <> n2`:
- `False`
- `n1 <> n1`
- `n2 <> n2`

Changing the name of the Program Definition, or the names of the variables, does not make the behavior go away.

**Comment by mattam82** [comment]
Ah indeed, Equations redefines the default `program_simpl` tactic. I recommend importing Program after Equations for now.

**Comment by mattam82** [comment]
No longer an issue I think
