### ISSUE TITLE
Matching on constructors with let-bindings

### ISSUE THREAD

**Issue by TheoWinterhalter** [mattam82/Coq-Equations#286]
Is pattern-matching on constructors with let-bindings not supported?

```coq
Inductive foo : nat -> Type :=
| foo_let n : let m := n + 2 in foo m.

Equations bar (n : nat) (x : foo n) : nat :=
  bar _ (foo_let x) := 3.
```
will raise
```coq
Non-exhaustive pattern-matching, no clause found for:
bar ?(m) (foo_let n0 m)
In context: 
  n0 : nat  m := n0 + 2 : nat
```
So it seems Equations is waiting for me to give a name to the let-bound variable, but of course, adding another variable yields
```
Constructor is applied to too many arguments
```

**Comment by mattam82** [comment]
Looks like a serious omission, let's see if it is easily fixable...
