### ISSUE TITLE
Questions/issues on documented grammar

### ISSUE THREAD

**Issue by Blaisorblade** [mattam82/Coq-Equations#295]
Here's the documented grammar — where's the nonterminal `f` declared? Should it actually be `progs`?

![image](https://user-images.githubusercontent.com/289960/85321961-d72f9c00-b4c5-11ea-9ced-3ccbacf51d83.png)

![image](https://user-images.githubusercontent.com/289960/85321989-e31b5e00-b4c5-11ea-90e9-ee4333c52408.png)

**Comment by mattam82** [comment]
You are right, it should be progs, it was confused with "f" for a constant (should be in green).
