### ISSUE TITLE
Issues building via opam for Coq 8.12

### ISSUE THREAD

**Issue by MSoegtropIMC** [mattam82/Coq-Equations#310]
I have issues build equations for Coq 8.12 via opam.

There is an opam package:

https://github.com/coq/opam-coq-archive/blob/master/extra-dev/packages/coq-equations/coq-equations.1.2.2%2B8.12/opam

referencing https://github.com/mattam82/Coq-Equations/archive/v1.2.2-8.12.tar.gz which is commit 9495e3e62a756a38365566fe6c6be6c000fd3f32

Coq 8.12 CI references this commit: 990b264fa1622be1550db08dae87a6aa48851e23

Can you please update the opam package - and possibly move it from extra-dev to released?

**Comment by palmskog** [comment]
@MSoegtropIMC in coq/opam-coq-archive#1345 I have already restricted the release `v1.2.2-8.12` release/tag to only support Coq 8.12+beta1 (which is the only version on OPAM it works with). This package will not be moved to `released`. I suggest @mattam82 makes a new release that works with 8.12.0, and we can create a new opam package from that.

Here is where  `v1.2.2-8.12` fails:
```
File "src/syntax.ml", line 260, characters 31-53:
260 |     | { CAst.v = CNotation (_,(InConstrEntrySomeLevel, "?( _ )"), _) } -> l
                                     ^^^^^^^^^^^^^^^^^^^^^^
Error: This variant pattern is expected to have type
         Constrexpr.notation_entry
       The constructor InConstrEntrySomeLevel does not belong to type Constrexpr.notation_entry
```

**Comment by MSoegtropIMC** [comment]
Yes, this is fixed in 990b264. As you said, we need a new release for 8.12.0.

**Comment by mattam82** [comment]
It should come soon: coq/coq-opam-archive#1356

**Comment by MSoegtropIMC** [comment]
Perfect thanks! One opam patch less in the Coq platform.

**Comment by mattam82** [comment]
Should be good now
