### ISSUE TITLE
Feature request: Optionally warn instead of erroring on a complete "Equations?" definition

### ISSUE THREAD

**Issue by kyoDralliam** [mattam82/Coq-Equations#321]
I really appreciate the `Equations?` mode that drops any leftover obligation into a single proof mode instead of using the (user-side) heavy obligation machinery. However if the tactic obligation happens to solve all goals then you get an error asking to remove the `?`, e.g
```coq
From Equations Require Import Equations.

Fail Equations? x : nat := x := 0.
(* The command has indeed failed with message:
   Equations definition is complete and requires no further proofs. Use the "Equations" command to define it. *)

(* Works *)
Equations x : nat := x := 0.
```

Could that be protected by a flag/an option to change the behaviour to a warning by default and do provide the definition instead of failing ? Even better if we can locally silence it on a single definition.

**Comment by mattam82** [comment]
Sadly, no. The async proof needs to know at parsing time if a definition is going to open the proof mode or not.

**Comment by mattam82** [comment]
We could rather not fail and leave an empty set of goals.

**Comment by mattam82** [comment]
I don't understand your suggestion, how would it be more practical to add `#[warn="-empty-goals]` than remove the single-character `?`?

**Comment by kyoDralliam** [comment]
Indeed the silencing part won't be useful. I would still prefer to have a warning instead of failing when prototyping (the scenario is that you type a definition where you might have goals to fill, and the definition fails because all obligations got discharged by inference).

**Comment by gares** [comment]
>  @gares right, there's no way to make such a thing work?

Indeed you would need to always open a proof, maybe a trivial one. You would need a syntactic flag, eg `by _` as the `:= _` in `Instance`.

On a side not, I have the feeling that this mode with just a bunch of goals is the one we would always wanted ;-) Great!

**Comment by mattam82** [comment]
I went with a configurable warning instead of an error if no goals are produced (so you have to write a trivial `Proof. Qed/Defined.` to finish the proof.
