### ISSUE TITLE
Provide an alias for the Derive vernacular to disambiguate with QuickChick

### ISSUE THREAD

**Issue by jakobbotsch** [mattam82/Coq-Equations#335]
QuickChick and Equations both define the `Derive X for Y.` vernacular which causes problems when using both plugins in one project. I suggest adding an alias to Equations such that `Equations Derive X for Y.` can be used to resolve this.

**Comment by jakobbotsch** [comment]
https://github.com/QuickChick/QuickChick/issues/206

**Comment by Lysxia** [comment]
Is there maybe some way for QuickChick to reuse the Derive command from Equations?

**Comment by mattam82** [comment]
Generic support should really come from Coq here. I'll add an alias.

**Comment by mattam82** [comment]
@Lysxia sadly it seems the derives in quickchick require additional arguments passed with `using` , so I don't see how to have a single command.

**Comment by Lysxia** [comment]
QuickChick has both variants with and without `using`, so couldn't some common plugin provide the two syntaxes, and then other plugins hook into it?

**Comment by mattam82** [comment]
Sure, that's also possible, but then if the plugin anticipates arbitrary grammars that won't be much different from using `VERNAC EXTEND`.

**Comment by mattam82** [comment]
Maybe that's another place where #[attributes] would help!
