### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.13

### ISSUE THREAD

**Issue by gares** [mattam82/Coq-Equations#336]
The Coq team is planning to release Coq 8.13-beta1 on December 7, 2020
and Coq 8.13.0 on January 7, 2020.

Your project is currently scheduled for being bundled in the Windows installer.

We are currently testing commit 2b341ceb72c6cc98c791db6cf23beb91b27fbc2e
on branch https://github.com/mattam82/Coq-Equations/tree/master
but we would like to ship a released version instead (a tag in git's slang).

Could you please tag that commit, or communicate us any other tag
that works with the Coq branch v8.13 at the *latest* 15 days before the
date of the final release?

Thanks!
CC: https://github.com/coq/coq/issues/12334

**Comment by gares** [comment]
The commit is now 3d44714eb76e452cdb172b4080befac0514a84ce

**Comment by mattam82** [comment]
The tag of 3d44714 is now created, and a corresponding release was created. https://github.com/mattam82/Coq-Equations/releases/tag/v1.2.3-8.13
