### ISSUE TITLE
Syntax error with ssreflect's rewrite -!xxx

### ISSUE THREAD

**Issue by Armael** [mattam82/Coq-Equations#338]
Using Coq 8.12.1 and Equations 1.2.3+8.12:

```coq
From Coq Require Import ssreflect.
Goal (forall n, n + 0 = n). intros. rewrite -!plus_n_O.
(* success *)
```

```coq
From Coq Require Import ssreflect.
From Equations Require Import Equations.
Goal (forall n, n + 0 = n). intros. rewrite -!plus_n_O. 
(* rewrite fails with:
Error:
Syntax error: '*' or [tactic:ssrrwargs] or [oriented_rewriter] expected after 'rewrite' (in [tactic:simple_tactic]).
*)
```

This seems to be the case even when equations has been transitively imported through a dependency.

**Comment by mattam82** [comment]
Yes, thorny conflict here... I'll put the notation (`Notation "!" := bang`) in a module that is not exported by default.

**Comment by mattam82** [comment]
Ah no, the problem is that an unrelated grammar was declaring "-!" as a token.

**Comment by Armael** [comment]
Thanks!
