### ISSUE TITLE
Aborted obligations linger

### ISSUE THREAD

**Issue by Tuplanolla** [mattam82/Coq-Equations#371]
#### Version

Coq 8.13.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following program fails unexpectedly
due to `f_inspect` getting the aborted obligation of `f_inspect_fail`
instead of the one generated for it.
However, if you rename `f_inspect_fail` into `f_inspect`,
`f_inspect` will get the right obligation and the failure will disappear.

```
From Coq Require Import Lia NArith.NArith Program.Basics.
From Equations Require Export Equations.

Obligation Tactic := idtac.

Section Context.

Import N.

Local Open Scope N_scope.

Context (f : N -> N) (mono : forall (a b : N) (l : a < b), f a < f b).

Equations f_bogus (n : N) : positive :=
  f_bogus n :=
    let m := f (succ n) - f n in
    match m with
    | N0 => _
    | Npos p => p
    end.
Next Obligation. intros n m. apply xH. Qed.

Equations f_inspect_fail (n : N) : positive :=
  f_inspect_fail n :=
    let m := f (succ n) - f n in
    match exist _ m (eq_refl m) with
    | exist _ N0 e => _
    | exist _ (Npos p) e => p
    end.
Next Obligation. intros n m _ _. Abort.

Equations f_inspect (n : N) : positive :=
  f_inspect n :=
    let m := f (succ n) - f n in
    match exist _ m (eq_refl m) with
    | exist _ N0 e => @const _ (m = N0) _ e
    | exist _ (Npos p) e => @const _ (m = Npos p) p e
    end.
Next Obligation. intros n m _ _ e. pose proof mono n (succ n) as l. lia. Qed.

End Context.
```

#### Notes

I know _with clauses_ can be used write `f_inspect`
without having to cast `e` using `const`,
but I am curious whether there is yet another way.

**Comment by mattam82** [comment]
This has more to do with the fact that "aborting" an obligation does not abort the definition, the aborted obligations stay and this is what you get from `Next Obligation`. You can do `Next Obligation of f_inspect_obligations` to get the one for `f_inspect`. The command `Obligations` tells you what are the remaining obligations at any point.
