### ISSUE TITLE
Coq-Equations-HoTT for a released version of Coq

### ISSUE THREAD

**Issue by co-dan** [mattam82/Coq-Equations#374]
Hi @mattam82 ,
as of now, I do not think it is possible to build the 8.13 branch of Coq-Equations with the latest version of the HoTT library.
I noticed that you recently [made some changes](https://github.com/mattam82/Coq-Equations/pull/367/files?file-filters%5B%5D=.v&file-filters%5B%5D=No+extension) that I think makes the development version of Coq-Equations to work with the latest version of the HoTT library.
Is there a chance that those changes can be backported to the 8.13 branch?
Or, in general, what is the current preferred way on working with Coq-Equations + the HoTT library?

**Comment by mattam82** [comment]
Indeed, only `master` enjoys the new setup for now, I just need to backport and make a release (there's a few other useful fixes there). Then the equations 1.2.5+8.13 opam package will have an optional dependency on coq-hott.8.13, so you'll get the HoTT variant installed automatically if you already have coq-hott.8.13 present.

**Comment by co-dan** [comment]
Thanks, I will wait for the backport then.

**Comment by mattam82** [comment]
Solved by the 1.3 release: https://github.com/mattam82/Coq-Equations/releases/tag/v1.3-8.13beta
