### ISSUE TITLE
Does coq-equations rename and confuse variable names?

### ISSUE THREAD

**Issue by drcicero** [mattam82/Coq-Equations#393]
Hi!

Maybe I am doing something wrong, but could it be that in some cases variable names are switched by coq-equations?

Take for example the following code that defines a here/there list index, such that 26 being the second element of a list can be represented as `(there here) : 26 ∈ (43 :: 26 :: 76 :: nil)`.

Using coq-equations I want to define a replace `repl` function that takes a list `R` and element `prev` and its index `idx`, and a value `next`, and returns a new list with `prev` at index `idx` replaced by `next`.

Notice, how I capture head and tail of the list in the variables `X` and `XS` on the left hand side of the equations;
however on the right hand side these variables names do not exists, instead, these variables are now called `idx` and `idx0`?

As a workaround one can continue with the wrong variable names, however I encountered this behavior also in larger code...

~~~
From Equations Require Import Equations.
Require Import List.

Inductive In {X} (x : X) : list X -> Type :=
| here {xs} : In x (x :: xs)
| there {y xs} : In x xs -> In x (y :: xs).
Derive Signature NoConfusion for In.
Notation " x ∈ xs " := (In x xs) (at level 70, xs at level 10).
Arguments here {X x xs}.
Arguments there {X x y xs} _.
Check (there here) : 26 ∈ (43 :: 26 :: 76 :: nil).

(* Does coq-equations mistake variable names sometimes? *)
Equations repl (R : list (Type -> Type)) prev (idx : prev ∈ R) (next : Type -> Type) : list (Type -> Type) :=
  repl (X :: XS) prev here         next := next :: idx (* idx works, but it should be X *);
  repl (X :: XS) prev (there idx') next := idx (* should be X *) :: (repl idx0 (* should be XS *) prev idx' next).
~~~

Further: If I annotate `prev` with a type explicitly, then coq-equations gives an error about `(X::XS)` being inaccessible.
Note, that it did give an error, when the type of `prev` is inferred like above, but only if it is given explicitly as below.
The error message makes the same name confusion, claiming `(X::XS)` would be identical to `(prev::idx)`, again confusing `idx` with `XS`.

Could the problem be related to inaccessible patterns and implicit arguments? Maybe `idx` and `idx0` are meant to be the freshly generated names for the implicit arguments of the real `idx`?

~~~
(* This renaming error may be related to inaccessible patterns? And makes errors very confusing: *)
Equations repl (R : list (Type -> Type)) (prev : Type -> Type) (idx : prev ∈ R) (next : Type -> Type) : list (Type -> Type) :=

  repl (X :: XS) prev here         next := next :: idx;
  (* actual:  "This pattern (X :: XS) must be inaccessible and equal to (prev :: idx)" *)
  (* -> ok X is prev; but XS is not inaccessible? *)

  repl (X :: XS) prev (there idx') next := idx :: (repl idx0 prev idx' next).
~~~

I tested the above code snippets and observed this behavior with coq-equations **1.2.3+8.13** and **1.3~beta+8.13**.

---

**EDIT:** I dont know anything about the internals of coq-equations, so there could be other reasons, but maybe it helps if i explain my current guess on what lead to this behavior:

1) Whether there is an inaccessible pattern error is influenced by whether I explicitly annotate the `prev` argument with a type (in this case: `Type -> Type`) or let it be inferred automatically. The error only happens if the type is given explicitly.

2) Implicit arguments of types seem to be bound to variable names that are derived from the corresponding variable name given in the first line of an equations together with a counter (0,1,2,...). So if I have a argument `idx`, its implicit arguments are bound to (`idx0`, `idx1`, `idx2`, ...). If the original argument (e.g., `idx`) is forced/inaccessible, then the name `idx` is free, and therefore the name derivation for the implicit argument does not add a counter but use the arguments name directly. Does that make sense?

**Comment by mattam82** [comment]
Indeed, it is the interaction with inaccessibles that is confusion: Equations should be promoting `idx#` (a generated name standing for the `{xs}` binding of `here`) to the `XS` that you input. It should also certainly error telling that `X` should be `?(prev)` (or `_`) or alternatively that `prev` should be `?(X)` depending on the fact that we split on `R` or `idx` first.

**Comment by mattam82** [comment]
This is now fixed. The upcoming 1.3~beta2 will have the fixed interpretation where no implicit shadowing will happen anymore.
