### ISSUE TITLE
Equations expects full pattern where no full pattern should be expected

### ISSUE THREAD

**Issue by yforster** [mattam82/Coq-Equations#401]
```
Definition inverts {X} {Y} (g : X -> Y) (f : Y -> X) := forall x, g (f x) = x.

From Equations Require Import Equations.

Definition inspect {X} (x : X) : {y | x = y}.
  now exists x.
Defined.
Notation "a eqn: E" := (exist _ a E) (at level 40).


#[tactic=congruence]
Equations R {X} {Y} (f : option X -> option Y) g (H : inverts g f) (x : X) : Y :=
  R f g H x with (inspect (f (Some x), f None)) :=
    { ((Some y, _) eqn: E1) := y ;
    | (None, Some y) eqn:E := y ;
    | (_ , _) eqn: E := _ }
.
```

yields

`Error: Expecting a pattern for R`

In my understanding, one does not have to repeat the full function head when using `with` clauses. Here it works: https://github.com/mattam82/Coq-Equations/blob/8.13/examples/STLC.v#L67

**Comment by mattam82** [comment]
You are missing a `|` in front of the first clause, this is used to disambiguate "full application" of R and "shorthand notation" for the newly introduced patterns. As arbitrary notations are supported as patterns, it would be wrong to add something to the grammar to lookahead and check that the first token is not an ident.
