### ISSUE TITLE
Dangling debug universe level in Equations definitions ?

### ISSUE THREAD

**Issue by kyoDralliam** [mattam82/Coq-Equations#445]
The following definition `foo` that should only make use of one (global, declared previously) universe level `u` fails to be defined if we specify that no universe levels should be involved (`@{}`), and elaborates if we admit additional universe levels (`@{+}`) but without actually binding any universe level !
```coq
From Equations Require Import Equations.

Universe u.
(* Same observed behaviour with and without universe polymorphism set *)
(* Set Universe Polymorphism. *)

Fail Equations foo@{} (u : unit) : Type@{u} :=
  | tt => unit.
(* The command has indeed failed with message: *)
(* Universe {debug.204} is unbound. *)

Equations foo@{+} (u : unit) : Type@{u} :=
  | tt => unit.

Set Printing Universes.
Print foo.
(* foo = fun u : unit => match u with *)
(*                       | tt => unit *)
(*                       end *)
(*      : unit -> Type@{u} *)

(* No problem with Definition *)
Definition  bar@{} (u : unit) : Type@{u} :=
  match u with | tt => unit end.
```

On coq 8.13 with equations 1.3~beta2+8.13

**Comment by mattam82** [comment]
That's tricky, equations always computes a non-algebraic variant of the universe of the type of the definition (here some universe `v` with `u+1 <= v`) to use it when necessary during pattern-matching simplification as it can be used in universe instances of the simplification constants. It looks hard to do this somewhat lazily...

**Comment by mattam82** [comment]
I managed to fix it for definitions that do not require using simplification constants. Otherwise equations might still generate fresh universes, as long as we don't handle arbitrary universes in universe instances. This might change in the future :)
