### ISSUE TITLE
Importing Equations 1.3 breaks std++'s 'simplify_eq' tactic

### ISSUE THREAD

**Issue by RalfJung** [mattam82/Coq-Equations#449]
The std++ library has its own `simplify_eq` tactic that overwrites the one in the standard library. This usually works fine, but something changed in Equations 1.3 that made this not work any more. The problem can be reproduced with the followng example:
```
Module Import tactics.
  Tactic Notation "simplify_eq" := idtac.
End tactics.

Goal True. Proof. simplify_eq. auto. Qed.

From Equations Require Import Equations.

Goal True. Proof. simplify_eq. auto. Qed.
```
Using Coq 8.13.2, this works fine with coq-equations 1.2.4+8.13 but breaks with 1.3~beta2+8.13, saying:
```
Error: Not a negated primitive equality.
```

**Comment by mattam82** [comment]
Indeed, the `Require Import Equations` was reloading the ltac plugin, undoing your redefinition.

**Comment by RalfJung** [comment]
This issue still seems to be a problem with version 1.3+8.18, has been [released](https://github.com/mattam82/Coq-Equations/releases/tag/v1.3-8.18) long after the issue got closed. Did something go wrong and the fix got lost somewhere?

**Comment by RalfJung** [comment]
In fact even the very latest version, 1.3.1, still has the problem, so I filed it as a new issue: https://github.com/mattam82/Coq-Equations/issues/628.
