### ISSUE TITLE
License: unclear

### ISSUE THREAD

**Issue by SnarkBoojum** [mattam82/Coq-Equations#496]
I packaged coq-equations for Debian, but it got rejected because of licensing issues: the file headers says LGPL 2.1, the opam says LGPL-2.1+.

There are files (theories/*/Relation*.v) out of coq: they are LGPL-2.1.

Could you clarify? Thanks.

**Comment by mattam82** [comment]
It is LGPL-2.1, I don't know why the or-later popped up in the opam package.

**Comment by palmskog** [comment]
The origin of the `LGPL-2.1-or-later` is a suggestion by me to try to clarify the ambiguous "LGPL 2.1", which is ambiguous: https://github.com/coq/opam-coq-archive/pull/999

However, it was just a suggestion, it was approved by @mattam82. So maybe we can clarify once and for all, and I'll update the opam archive: the SPDX identifier of the Equations license is [`LGPL-2.1-only`](https://spdx.org/licenses/LGPL-2.1-only.html)?
