### ISSUE TITLE
Multiple problems with list

### ISSUE THREAD

**Issue by eponier** [mattam82/Coq-Equations#500]
To play a bit with Equations, I tried to generate an eq_dec procedure for lists, but observed multiple problems.

First, if I call `Derive NoConfusion EqDec for list.`, an obligation remains which is exactly the goal that I want Equations to solve. And if admit the obligation, I have a universe error.
```
Derive NoConfusion EqDec for list.
Next Obligation. Admitted.
(* The 1st term has type "Type@{max(Set,list.u0)}" which should be coercible to "Type@{dec_eq.u0}". *)
```

Apparently, Equations expects `Set` instead of `Type`. But if I define another version of lists using `Set`, I get an anomaly when trying to admit the obligation.
```
Inductive list (A:Set) :=
| nil
| cons : A -> list A -> list A.

Derive NoConfusion EqDec for list.
Next Obligation. Admitted.
(* Anomaly "Uncaught exception Environ.NotEvaluableConst(0)." Please report at http://coq.inria.fr/bugs/. *)
```

Apparently, Equations has a hard time coping with the parameter, so we can try to put everything in a section. And we can assume that the type variable has a decidable equality (otherwise, we observe more or less the same behaviour as before).

With `Type`, we still have a universe error.
```
Section LIST.

Variable (A:Type) (eq_dec : EqDec A).

Inductive list : Type :=
| nil
| cons : A -> list -> list.

Derive NoConfusion EqDec for list.
(* The 1st term has type "Type@{max(Set,Top.324)}" which should be coercible to "Type@{dec_eq.u0}". *)

End LIST.
```
With `Set`, we finally have something working.
```
Section LIST.

Variable (A:Set) (eq_dec : EqDec A).

Inductive list : Type :=
| nil
| cons : A -> list -> list.

Derive NoConfusion EqDec for list.

Check list_eqdec. (* : forall x y : list, dec_eq x y *)

End LIST.
```
This seems a lot of trouble for a standard type like `list`. Have I misunderstood something?

Version of Coq: 8.15
Version of Equations: 1.3+8.15

**Comment by laMudri** [comment]
Here is the minimal failing example I came across [just last week](https://coq.zulipchat.com/#narrow/stream/237659-Equations-devs-.26-users/topic/Derive.20EqDec.20for.20parametrised.20types) too:

```coq
From Equations Require Import Equations.

Section box.
  Universe u.
  Context {A : Type@{u}} `(EA : EqDec A).

  Inductive box : Type@{u} :=
  | pack : A -> box.
  Derive NoConfusion for box.
  Fail Derive EqDec for box.
End box.

(*
box_eqdec has type-checked, generating 1 obligation
Solving obligations automatically...
No more obligations remaining

Unable to compute diffs: Input string is not lexable
The command has indeed failed with message:
Illegal application:
The term "@dec_eq" of type "forall A : Type, A -> A -> Set"
cannot be applied to the terms
 "box" : "Type"
 "x" : "box"
 "y" : "box"
The 1st term has type "Type@{u}" which should be coercible to
 "Type@{dec_eq.u0}".
 *)
```

**Comment by mattam82** [comment]
Indeed, equations was missing a call to compute the universe constraints of the application `dec_eq (list A) x y`, fixed now in https://github.com/mattam82/Coq-Equations/pull/502

**Comment by eponier** [comment]
I've just tested the fix. As far as I can tell, it only fixes the problem about `Set` vs `Type`. Is it normal that we cannot call `Derive NoConfusion EqDec for list.` directly (it seems we have to define a new type in a section instead)?
