### ISSUE TITLE
Recursive definition is ill-formed

### ISSUE THREAD

**Issue by hflsmax** [mattam82/Coq-Equations#542]
The following Equations definition is valid but not accepted by Coq. This issue was originally reported at [link](https://coq.zulipchat.com/#narrow/stream/237659-Equations-devs-.26-users/topic/Recursive.20definition.20is.20ill-formed.2E/near/339441776) and confirmed to be a bug by @mattam82 

```
Inductive A : Type := A_mk : B -> A
with B : Type := B_mk : C -> B
with C : Type := C_mk : A -> C.

From Equations Require Import Equations.

Equations fA (a : A) : False := {
  fA (A_mk b) => fB b;
} where fB : B -> False := {
  fB (B_mk c) => fC c;
} where fC : C -> False := {
  fC (C_mk a) => fA a;
}.
```

**Comment by mattam82** [comment]
You need to replace "where" with "with" here as it is mutual inductive. "where" is useful with nested inductive types which are distinct from mutual ones.
