### ISSUE TITLE
Online tutorial outdated.

### ISSUE THREAD

**Issue by yurug** [mattam82/Coq-Equations#56]
This tutorial:
https://www.irif.fr/~sozeau/research/coq/equations-intro.html
uses
```
Require Import Equations.
```
to import Equations while it should be
```
From Equations Require Import Equations.
```
(which is a bit weird from a beginner's point of view. I would prefer:
```
From Equations Require Import All.
```
or something like that.)

**Comment by mattam82** [comment]
This is an old link, the new one is: http://mattam82.github.io/Coq-Equations/examples/equations_intro.html

I should redirect from my webpage.
