### ISSUE TITLE
Equations hides definitions from Init.

### ISSUE THREAD

**Issue by yurug** [mattam82/Coq-Equations#57]
This is probably more an issue of Program but Requiring Equations has an unpleasant side-effect which breaks existing code: it hides ``Init.Wf.Fix_eq`` with its own definition of ``Wf.Fix_eq``.

Since ``Init`` is implicitely imported in the scope, a user might take some time to understand and fix the issue (namely by rewriting its ``Fix_eq`` occurrences to ``Init.Wf.Fix_eq``).

**Comment by mattam82** [comment]
Indeed that's more a Program issue, closing here.
