### ISSUE TITLE
Variables introduced by pattern matching are not lexical scoped

### ISSUE THREAD

**Issue by jwiegley** [mattam82/Coq-Equations#61]
```
Equations bug (x : nat) : nat :=
  bug O := O;
  bug (S n) <= 2 => {
   | x <= 3 => {
     | x => x
   }
  }.

Compute bug 5.
```

This yields `2` instead of `3`.

**Comment by mattam82** [comment]
Ha, good catch, we need to shadow...

**Comment by mattam82** [comment]
Actually, upon further thinking this is forbidden. Contrary to match .. with, you cannot shadow the previous pattern variables: here the last clause dessugars to bug (S n) x x which would be non-linear.
Also, implementing renaming during desugaring, suddenly changing the meaning of [x] in branches that bind it again would be a mess.
