### ISSUE TITLE
Have access to the body of a recursive function while defining it

### ISSUE THREAD

**Issue by jad-hamza** [mattam82/Coq-Equations#67]
Program Fixpoint and Equations here generate an obligation which is not provable. This example can be solved by refining the return type of `f`, but in general I wonder whether it could be possible to have access to the rewrite lemmas generated by Equations, while proving the obligations generated in the function. It should be sound to have access the rewrite lemmas for smaller recursive calls. 

```coq
Require Equations.Equations.
      
Equations f (n: nat): nat :=
  f n := match n with
         | 0 => 0
         | S n' =>
           let H: f n' = 0 := _ in
           0
         end.

Next Obligation.
  (* Prove f n' = 0, given f: nat -> nat *)
Abort.
````

**Comment by mattam82** [comment]
This is not possible in general. You might want to look at other techniques like the Bove Capretta method.
