### ISSUE TITLE
Problem with coq-equations installation

### ISSUE THREAD

**Issue by paola-giannini** [mattam82/Coq-Equations#68]
I have very little knowledge about how to install packages, so I just followed the directions on how to install coq-equation on my mac (I have High Sierra), and I got the following problem:

bash-3.2$ opam install coq-equations.1.0+8.7
The following actions will be performed:
  ∗  install camlp5        7.05               [required by coq]
  ∗  install conf-m4       1                  [required by ocamlfind]
  ∗  install ocamlfind     1.7.3-1            [required by coq]
  ∗  install num           1.1                [required by coq]
  ∗  install coq           8.7.2              [required by coq-equations]
  ∗  install coq-equations 1.0+8.7
===== ∗  6 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[coq-released] https://coq.inria.fr/opam/released/archives/coq-equations.1.0+8.7+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/num.1.1+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/camlp5.7.05+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlfind.1.7.3-1+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/coq.8.7.2+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
∗  installed camlp5.7.05
∗  installed conf-m4.1
∗  installed ocamlfind.1.7.3-1
∗  installed num.1.1
∗  installed coq.8.7.2
[ERROR] The compilation of coq-equations failed at "make -j1".
Processing  6/6: [coq-equations: rm]
#=== ERROR while installing coq-equations.1.0+8.7 =============================#
# opam-version 1.2.2
# os           darwin
# command      make -j1
# path         /Users/giannini/.opam/4.06.1/build/coq-equations.1.0+8.7
# compiler     4.06.1
# exit-code    2
# env-file     /Users/giannini/.opam/4.06.1/build/coq-equations.1.0+8.7/coq-equations-88650-5788a7.env
# stdout-file  /Users/giannini/.opam/4.06.1/build/coq-equations.1.0+8.7/coq-equations-88650-5788a7.out
# stderr-file  /Users/giannini/.opam/4.06.1/build/coq-equations.1.0+8.7/coq-equations-88650-5788a7.err
### stdout ###
# [...]
# CAMLDEP src/principles_proofs.ml
# CAMLDEP src/splitting.ml
# CAMLDEP src/covering.ml
# CAMLDEP src/syntax.ml
# CAMLDEP src/depelim.ml
# CAMLDEP src/eqdec.ml
# CAMLDEP src/subterm.ml
# CAMLDEP src/sigma_types.ml
# CAMLDEP src/derive.ml
# CAMLDEP src/equations_common.ml
### stderr ###
# [...]
# /bin/sh: /opt/local/bin/ocamlfind: No such file or directory
# /bin/sh: /opt/local/bin/ocamlfind: No such file or directory
# /bin/sh: /opt/local/bin/ocamlfind: No such file or directory
# /bin/sh: /opt/local/bin/ocamlfind: No such file or directory
# /bin/sh: /opt/local/bin/ocamlfind: No such file or directory
# /bin/sh: /opt/local/bin/ocamlfind: No such file or directory
# /bin/sh: /opt/local/bin/ocamlfind: No such file or directory
# /bin/sh: /opt/local/bin/ocamlfind: No such file or directory
# /bin/sh: /opt/local/bin/ocamlfind: No such file or directory
# Makefile:703: *** "Cannot find the 'ocamlfind' binary used to build Coq (/opt/local/bin/ocamlfind). Pre-compiled binary packages of Coq do not support compiling plugins this way. Please download the sources of Coq and run the Windows build script.".  Stop.

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions failed
  ∗  install coq-equations 1.0+8.7
The following changes have been performed
  ∗  install camlp5    7.05   
  ∗  install conf-m4   1      
  ∗  install coq       8.7.2  
  ∗  install num       1.1    
  ∗  install ocamlfind 1.7.3-1

The former state can be restored with:
    opam switch import "~/.opam/4.06.1/backup/state-20180311085727.export"
bash-3.2$ 

can you tell me what to do?         Paola

**Comment by mattam82** [comment]
That's strange. What does 
``# which ocamlfind``
give you now? What about
``# eval `opam config env` ``
``# which ocamlfind``

If the path changes then maybe trying again 
``# opam install coq-equations.1.0+8.7``
will succeed.

I'm trying to reproduce a fresh installation of the same set of packages on my computer to see.

**Comment by paola-giannini** [comment]
no it did not change, here is the result

===============================

bash-3.2$ which ocamlfind
/Users/giannini/.opam/4.01.0+BER/bin/ocamlfind
bash-3.2$ opam config env
CAML_LD_LIBRARY_PATH="/Users/giannini/.opam/4.06.1/lib/stublibs"; export CAML_LD_LIBRARY_PATH;
OPAMUTF8MSGS="1"; export OPAMUTF8MSGS;
MANPATH=":/Users/giannini/.opam/4.06.1/man"; export MANPATH;
PERL5LIB="/Users/giannini/.opam/4.06.1/lib/perl5:"; export PERL5LIB;
OCAML_TOPLEVEL_PATH="/Users/giannini/.opam/4.06.1/lib/toplevel"; export OCAML_TOPLEVEL_PATH;
PATH="/Users/giannini/.opam/4.06.1/bin:/Users/giannini/anaconda/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin"; export PATH;
bash-3.2$ which ocamlfind
/Users/giannini/.opam/4.01.0+BER/bin/ocamlfind

===============================

**Comment by mattam82** [comment]
You need to do ``eval `opam config env` `` so that the paths are correctly changed and ocamlfind is found in the 4.06.1 "switch". However, it seems Coq itself was configured with an `ocamlfind` in `/opt/local/bin/` which looks wrong. Apparently it does not even exist and it should also rather be the one in `/Users/giannini/.opam/4.06.1/bin`. So maybe after the ``eval `opam config env` ``, you can try ``opam remove coq`` and ``opam install coq-equations.1.0+8.7`` again so that Coq is properly configured to use the right ocamlfind.

**Comment by paola-giannini** [comment]
it did change, my fault, and now I have coq-equations installed
      thanks a lot  Paola

**Comment by mattam82** [comment]
I cannot reproduce the problem:
```
opam install coq-equations.1.0+8.7
The following actions will be performed:
  ∗  install conf-m4       1                  [required by ocamlfind]
  ∗  install camlp5        7.05               [required by coq]
  ∗  install ocamlfind     1.7.3-1            [required by coq]
  ∗  install num           1.1                [required by coq]
  ∗  install coq           8.7.2              [required by coq-equations]
  ∗  install coq-equations 1.0+8.7
===== ∗  6 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[my-released] http://coq.inria.fr/opam/released/archives/coq-equations.1.0+8.7+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/num.1.1+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/camlp5.7.05+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlfind.1.7.3-1+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/coq.8.7.2+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
∗  installed conf-m4.1
∗  installed ocamlfind.1.7.3-1
∗  installed num.1.1
∗  installed camlp5.7.05
∗  installed coq.8.7.2
∗  installed coq-equations.1.0+8.7
Done.
```

**Comment by mattam82** [comment]
Cool!

**Comment by paola-giannini** [comment]
I'm sorry I'm such a zombi when it comes to installations. I'm more comfortable with proving theorems!
