### ISSUE TITLE
Fatal error: out of memeory

### ISSUE THREAD

**Issue by TimRichter** [mattam82/Coq-Equations#69]
Hi,
coqc (version 8.7.2 with coq-equations 1.0+8.7 
on Ubuntu Linux 16.04) tries for about 10 minutes
and finally dies with "Fatal error: out of memory" on this:

    Require Import Fin.
    From Equations Require Import Equations.
    
    (* crashes Coq *)
    Equations invertFin {n : nat} (x : Fin.t n) : Fin.t n :=
    invertFin {n:=0} x           :=! x;
    invertFin {n:=(S 0)}     F1  := F1;
    invertFin {n:=(S (S n))} F1  := FS (invertFin F1);
    invertFin {n:=(S (S n))} (FS x) <= invertFin x => {
                                    | F1      := F1;
                                    | (FS ix) := _}.

Strange, isn't it?
Best regards,
Tim

**Comment by mattam82** [comment]
Ooops, that's the default obligation tactic of Program (independent of Equations) that tries to solve this goal:

```
  invertFin : forall n : nat, t n -> t n
  wildcard3 : nat
  x : t (S wildcard3)
  ix : t wildcard3
  ============================
  t (S (S wildcard3))
```
It calls typeclasses eauto which loops infinitely because of the invertFin hypothesis. I'll open an issue to give a bound to that proof search.

**Comment by mattam82** [comment]
The workaround is to do for example:
```
Obligation Tactic := idtac.

Equations invertFin {n : nat} (x : Fin.t n) : Fin.t n :=
invertFin {n:=0} x           :=! x;
invertFin {n:=(S 0)}     F1  := F1;
invertFin {n:=(S (S n))} F1  := FS (invertFin F1);
invertFin {n:=(S (S n))} (FS x) <= invertFin x => {
                                | F1      := F1;
                                | (FS ix) := _}.

Next Obligation. intros. depelim x. Defined.
Next Obligation. constructor. Defined.
```

Note however that your definition is not structurally recursive `invertFin F1` in the third clause is not a valid recursive call.
