### ISSUE TITLE
Obligation tactic not used when declaring an Equation

### ISSUE THREAD

**Issue by jad-hamza** [mattam82/Coq-Equations#71]
Tactic `t` can solve (unsoundly) the goal generated by content, but the obligation remains after the declaration of Equation. Am I missing something to specify that goals should be solved automatically using `t`?

On the final line, when I do `Next Obligation`, tactic  `t` is used automatically and the goal is solved.

```coq
Require Equations.Equations.

Axiom unsupported: False. 
Axiom ignore_termination: nat.  

Ltac t := intros; match goal with
  | |- (?T < ?T)%nat =>
    unify T ignore_termination; apply False_ind; exact unsupported
  end.

Obligation Tactic := t.

Equations content (n: nat): nat := 
content n by rec ignore_termination lt :=
content n := content n.

Next Obligation. Qed. (* succeeds *)
```

**Comment by mattam82** [comment]
The problem was that the default obligation tactic didn't apply to recursive call obligations.
