### ISSUE TITLE
Equations lemma takes a long time to prove

### ISSUE THREAD

**Issue by jad-hamza** [mattam82/Coq-Equations#75]
The `Admit` in the end takes 30 seconds to go through. Apparently it is due to lemma  `foldLeft_unfold_eq' taking a while to prove. (thanks to the people on the coq IRC channel)

Removing  `(l: List T)` from either `f_type` or  `foldLeft_type` makes the `Admit` go through quite fast. 
Replacing Cons_type with List as well.

```coq
Require Equations.Equations.

Set Program Mode.

Definition ifthenelse b A (e1: true = b -> A) (e2: false = b -> A): A. Admitted.
  
Definition List (T: Type): Type. Admitted.
Definition isCons (T: Type) (src: List T): bool. Admitted.
Definition Cons_type (T: Type): Type := {src: List T | (isCons T src = true)}.
Definition head (T: Type) (src: Cons_type T): T. Admitted.
Definition tail (T: Type) (src: Cons_type T): List T. Admitted.
Definition f_type (T R: Type) (l: List T): Type := R -> (T -> R).
Definition foldLeft_type (T R: Type) (l: List T): Type := R.

Equations foldLeft (T R: Type) (l: List T) (z: R) (f: f_type T R l): foldLeft_type T R l := 
foldLeft T R l z f by rec 0 lt :=
foldLeft T R l z f :=
  ifthenelse (isCons _ l) R
             (fun _ => foldLeft T R (tail T l) (f z (head T l)) f)
             (fun _ => z).

Admit Obligations.
```

**Comment by mattam82** [comment]
It's (almost) instantaneous now, but the following lemma proof automation fails and uncovered an orthogonal bug in Coq.

**Comment by jad-hamza** [comment]
For reference, the other example we discussed: https://gist.github.com/jad-hamza/db1f3c084b30b57bd2bf32ed62089719

**Comment by mattam82** [comment]
This is now fixed in master and will be part of the upcoming release.
