### ISSUE TITLE
Implicit Arguments of Constructors in Patterns

### ISSUE THREAD

**Issue by fakusb** [mattam82/Coq-Equations#77]
The multiple possible ways to give arguments to constructors are a bit confusing to me. 
```
From Equations Require Import Equations.
Require Vector. 
 Equations test {X n} (v : vector X (S n)) : vector X 0 :=
    {
      test Vector.cons := Vector.nil
    }.

  Equations test1 {X n} (v : vector X (S n)) : vector X n :=
    {
      test1 (Vector.cons a) := a
    }.

  Equations test2 {X n} (v : vector X (S n)) : vector X n :=
    {
      test2 (Vector.cons n a) := a
    }.

  Equations test3 {X n} (v : vector X (S n)) : vector X n :=
    {
      test3 (Vector.cons X n a) := a
    }.
```

**Comment by mattam82** [comment]
Indeed, one can provide any subset. Given the reports I'll fix it to enforce the same arity as the constructor (modulo implicits).

**Comment by mattam82** [comment]
The upcoming release uses the standard Coq parser to parse left-hand sides, so it is entirely predictable. Only test2 works, and one can use [(@Vector.cons _ x n a) := a] to bind the (implicit) index.
