### ISSUE TITLE
Variable defined by "where" sometimes "not found in the current environment"

### ISSUE THREAD

**Issue by ANogin** [mattam82/Coq-Equations#79]
In attempting to work around issue #78 as follows:
```
From Coq.Lists Require Import List.
From Equations Require Import Equations.

(* This type is from VST: https://github.com/PrincetonUniversity/VST/blob/v2.1/floyd/compact_prod_sum.v#L6 *)
Fixpoint compact_prod (T: list Type): Type :=
  match T with
  | nil => unit
  | t :: nil => t
  | t :: T0 => (t * compact_prod T0)%type
  end.

(* The rest is a nonsensical, just to give a minimalistic reproducible example *)
Inductive foo :=
| Nat : foo
| List : foo.

Definition foo_type (f:foo) : Type :=
  match f with
  | Nat => nat
  | List => list unit
  end.

Equations num (f:foo) (val:foo_type f) : nat :=
  num Nat val := val;
  num List val := length val.

Equations sum (fs : list foo) (val: compact_prod (map foo_type fs)) : nat := {
  sum nil _ := 0;
  sum (cons f tl) val := sum_aux f tl val }
where (struct fs) sum_aux (f:foo) (fs : list foo) (val: compact_prod (map foo_type (f::fs))) : nat := {
  sum_aux f nil val := num f val;
  sum_aux f (cons hd tl) val := num f (fst val) + sum_aux hd tl (snd val)}.
```
I got ```The variable sum_aux was not found in the current environment.``` for the occurrence of sum_aux in the 2nd equation for sum.

P.S. I was actually intending to create a small test case for another error I am getting in trying to work around issue #78 in my actual development, but this issue made it hard to reproduce the other one.

**Comment by anton-trunov** [comment]
I guess I hit the same issue.

The following works:
```coq
Equations foo (n : nat) : nat :=
foo n := bar (S n)
where bar (n : nat) : nat :=
bar n := n.
```

This snippet 
```coq
Equations foo (n : nat) : nat :=
foo n := bar (S n)
where bar (n : nat) : nat :=
bar O := O;
bar (S n) := bar n.
```
produces the following error message:
> Error: The variable bar was not found in the current environment.

pointing to the `bar (S n) := bar n.` clause as the source of the error.

When adding curly braces like so
```coq
Equations foo (n : nat) : nat := {
foo n := bar (S n) }
where bar (n : nat) : nat :=
bar O := O;
bar (S n) := bar n.
```

the error message stays the same, but this time the line that gets marked as the source is `foo n := bar (S n) }`.

**Comment by anton-trunov** [comment]
It only works if `bar` mentiones `foo`:

```coq
Equations foo (n : nat) : nat := {
foo n := bar n }
where bar (n : nat) : nat := {
bar O := O;
bar (S n) := foo n }.
```

However, if I remove the braces it fails again:

```coq
Fail Equations foo (n : nat) : nat := 
foo n := bar n
where bar (n : nat) : nat :=
bar O := O;
bar (S n) := foo n.
```

**Comment by mattam82** [comment]
Interesting... there is a syntactic check indeed for recursion
Le mar. 1 mai 2018 à 16:27, Anton Trunov <notifications@github.com> a
écrit :

**Comment by mattam82** [comment]
Next on my list, indeed the syntactic check is too crude to determine whether things are mutually recursive or not, I will have to build a dependency graph it seems.

**Comment by mattam82** [comment]
Actually, these can't be mutually recursive:
```
Fixpoint foo (n : nat) : nat := 
  bar n
with bar (n : nat) : nat :=
       match n with 0 => 0 | S n => foo n end.
```
Fails.

**Comment by mattam82** [comment]
So it's rather that foo is recursive while bar isn't (it's just a definition in this case).

**Comment by mattam82** [comment]
Also there are examples where you want the where clause itself to be recursive, that requires a few changes as well.

**Comment by mattam82** [comment]
This now works by specifying "by struct fs" for both "sum" and "sum_aux". The fix is in master and will be part of the upcoming release.
