### ISSUE TITLE
Notations do not always work in pattern-matching

### ISSUE THREAD

**Issue by anton-trunov** [mattam82/Coq-Equations#81]
The following snippet produces an error message.
```coq
Require Import Coq.Lists.List.
Import ListNotations.
From Equations Require Import Equations.

Equations app {A} (l l' : list A) : list A :=
app [] l' := l' ;                                  (* <- here notations work *)
app (a :: l) l' := a :: (app l l').
```

The error message is
> Error: Syntax error: ')' expected after [lpatt] (in [patt]).

It works if I change `(a :: l)` with `cons a l`.

Tested with Coq 8.8.0, Equations 1.0, both installed via OPAM.

**Comment by mattam82** [comment]
Yes, this is not easy to fix, I basically need to extend the pattern parser of Coq.

**Comment by mattam82** [comment]
This is now fixed in master, one can use notations freely in patterns.
