### ISSUE TITLE
Ability to drop names in the type declaration of a function

### ISSUE THREAD

**Issue by anton-trunov** [mattam82/Coq-Equations#82]
I'd like to be able to define functions like so:

```coq
From Coq Require Import List.
From Equations Require Import Equations.

Equations app {A} : list A -> list A -> list A :=
app xs ys := fold_right cons ys xs.
```

but it fails with the following error message:

>Non-exhaustive pattern-matching, no clause found for:
app A
In context: 
A : Type

Is there a workaround?

**Comment by mattam82** [comment]
Indeed, a few users reported the problem already, that shouldn’t be too hard to implement. I suppose in e.g Agda they use the number of patterns of the first clause to figure out how to split the prototype into arguments and results.

**Comment by mattam82** [comment]
This now works out of the box.
