### ISSUE TITLE
acc_A_B_lexprod is opaque and this blocks evaluation

### ISSUE THREAD

**Issue by anton-trunov** [mattam82/Coq-Equations#87]
We cannot compute with Ackermann's function (see e.g. [ack.v](https://github.com/mattam82/Coq-Equations/blob/master/test-suite/ack.v)):

```coq
Example test1 : ack (1, 2) = 4 := eq_refl.
```

Here is the error message:
>The term "eq_refl" has type "ack (1, 2) = ack (1, 2)"
while it is expected to have type "ack (1, 2) = 4" (cannot unify 
"ack (1, 2)" and "4").

**Comment by anton-trunov** [comment]
Is there a reason to keep `acc_A_B_lexprod` opaque?

**Comment by mattam82** [comment]
Nope, no good reason
