### ISSUE TITLE
Slowness in the simp tactic (5s to complete)

### ISSUE THREAD

**Issue by jad-hamza** [mattam82/Coq-Equations#95]
Very likely to be related to (https://github.com/coq/coq/issues/7585).

In this multifile project, using `simp transport in *` takes 5s to complete.

Removing the line transport t T by rec 0 lt := makes the problem disappear, and putting all the code in the same file also makes the problem disappear. (the rewrite then takes 0.001s).

Zip file of the project: [simp-slowness.zip](https://github.com/mattam82/Coq-Equations/files/2030106/simp-slowness.zip)

File1.v

```coq
Require Import Equations.Equations.
Require Import Omega.

Inductive type: Set :=
  | T_bool: type
  | T_prod: type -> type -> type.

Equations transport (t: nat) (T: type): Prop :=
  transport t T by rec 0 lt :=

  transport t T_bool := True;

  transport t (T_prod U V) :=
    transport t U /\
    transport t V.

Next Obligation. Admitted.
Next Obligation. Admitted.

(* obligation generated for transport_ind_fun *)
Next Obligation.
  generalize t.
  induction T; repeat intuition || simp transport in *.
Defined.
```

File2.v

```coq
Require Import Top.File1.
Require Import Omega.
Require Import Equations.Equations.

Lemma l:
  forall T t,
    transport t T ->
    forall t',
      transport t' T.
Proof.
  induction T; intuition auto; try omega.
  - Set Ltac Profiling.
    simp transport in *.
Abort.
```

**Comment by mattam82** [comment]
As analyzed on gitter, this is due to "transport" being seen transparent outside the first module.

**Comment by mattam82** [comment]
This is now fixed in master, Opacity of transport is registered by the first module.
