### ISSUE TITLE
Unexpected obligation generated for *_ind_fun

### ISSUE THREAD

**Issue by jad-hamza** [mattam82/Coq-Equations#96]
In this example, an obligation in generated for `transport_ind_fun`, which is not solved automatically.

```coq
Require Import Equations.Equations.

Inductive type: Set :=
  | T_bool: type
  | T_prod: type -> type -> type.

Equations transport (t: nat) (T: type): Prop :=
  transport t T by rec 0 lt :=

  transport t T_bool := True;

  transport t (T_prod U V) :=
    transport t U /\
    transport t V.

Next Obligation. Admitted.
Next Obligation. Admitted.

(* obligation generated for transport_ind_fun *)
Next Obligation.
  induction T; repeat intuition || simp transport in *.
Defined.
```

**Comment by mattam82** [comment]
Indeed, the automated tactic fails to reuse the well-foundedness arguments used in the definition (here 0 < 0) because the corresponding lemmas (printable using Print HindDb transport_wf_obligations) are too general.

**Comment by mattam82** [comment]
We should allow shrinking of these obligations to their minimal context so they can be reused.

**Comment by mattam82** [comment]
The obligations are now shrinked properly so that the "0 < 0" proofs can be found while proving the induction principle. In master, Equations doesn't use the obligations mode anymore but rather the proof refinement mode (with multiple subgoals if there are multiple obligations), and the by rec syntax was simplified, so it looks like this:

```coq
Axiom cheat : 0 < 0.

Equations? transport (t: nat) (T: type): Prop by rec 0 lt :=

  transport t T_bool := True;

  transport t (T_prod U V) :=
    transport t U /\
    transport t V.
Proof. apply cheat. apply cheat. Defined.
```
